[[manager.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

# [[manager.prepend_keymap]]
# on   = "<Esc>"
# run  = "quit"
# desc = "Exit yazi"

[[manager.prepend_keymap]]
on   = [ "c", "a" ]
run  = "plugin compress"
desc = "Archive selected files"

[[manager.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[manager.prepend_keymap]]
on   = "<S-Up>"
run  = "arrow -5"
desc = "Move cursor up 5 lines"

[[manager.prepend_keymap]]
on   = "<S-Down>"
run  = "arrow 5"
desc = "Move cursor down 5 lines"

[[manager.prepend_keymap]]
on   = "K"
run  = "arrow -5"
desc = "Move cursor up 5 lines"

[[manager.prepend_keymap]]
on   = "J"
run  = "arrow 5"
desc = "Move cursor down 5 lines"

[[manager.prepend_keymap]]
on  = "y"
run = [ 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]

[[manager.prepend_keymap]]
on  = "u"
run = "plugin restore"
desc = "Restore last deleted files/folders"
