# Vesper theme for Yazi
# Based on the VSCode Vesper theme

# Main colors from Vesper theme
# Background: #101010
# Foreground: #FFFFFF
# Accent: #FFC799 (orange)
# Green: #99FFE4
# Red: #FF8080
# Gray: #A0A0A0

[manager]
cwd = { fg = "#A0A0A0" }

# Hovered
hovered = { fg = "#FFC799", bg = "#232323" }
preview_hovered = { fg = "#FFC799", bg = "#232323" }

# Find
find_keyword = { fg = "#FFC799", bold = true }
find_position = { fg = "#A0A0A0", bg = "#232323" }

# Markers
marker_copied = { fg = "#99FFE4", bg = "#101010" }
marker_cut = { fg = "#FF8080", bg = "#101010" }
marker_marked = { fg = "#FFC799", bg = "#101010" }
marker_selected = { fg = "#FFC799", bg = "#101010" }

# Tab
tab_active = { fg = "#FFC799", bg = "#161616" }
tab_inactive = { fg = "#A0A0A0", bg = "#101010" }
tab_width = 3

# Count
count_copied = { fg = "#99FFE4", bg = "#101010" }
count_cut = { fg = "#FF8080", bg = "#101010" }
count_selected = { fg = "#FFC799", bg = "#101010" }

# Border
border_symbol = "│"
border_style = { fg = "#282828" }

# Highlighting
syntect_theme = ""

[mode]
# Normal mode
normal_main = { fg = "#FFFFFF", bg = "#101010" }
normal_alt = { fg = "#A0A0A0", bg = "#101010" }

# Select mode
select_main = { fg = "#FFFFFF", bg = "#232323" }
select_alt = { fg = "#FFC799", bg = "#232323" }

# Unset mode
unset_main = { fg = "#FFFFFF", bg = "#101010" }
unset_alt = { fg = "#A0A0A0", bg = "#101010" }

[status]
# Status bar
overall = { fg = "#A0A0A0", bg = "#101010" }
sep_left = { open = "[", close = "]" }
sep_right = { open = "[", close = "]" }

# Permissions
perm_type = { fg = "#A0A0A0" }
perm_read = { fg = "#99FFE4" }
perm_write = { fg = "#FFC799" }
perm_exec = { fg = "#FF8080" }
perm_sep = { fg = "#505050" }

# Progress
progress_label = { fg = "#FFC799", bold = true }
progress_normal = { fg = "#99FFE4", bg = "#232323" }
progress_error = { fg = "#FF8080", bg = "#232323" }

[which]
# Which key
cols = 2
mask = { bg = "#101010", bold = true }
cand = { fg = "#FFC799" }
rest = { fg = "#A0A0A0" }
desc = { fg = "#FFFFFF" }
separator = " → "
separator_style = { fg = "#505050" }

[confirm]
# Confirm dialog
border = { fg = "#282828" }
title = { fg = "#FFC799", bold = true }
content = { fg = "#FFFFFF" }
list = { fg = "#A0A0A0" }
btn_yes = { fg = "#99FFE4", bold = true }
btn_no = { fg = "#FF8080", bold = true }
btn_labels = ["Yes", "No"]

[spot]
# Spot dialog
border = { fg = "#282828" }
title = { fg = "#FFC799", bold = true }
tbl_col = { fg = "#FFC799", bold = true }
tbl_cell = { fg = "#FFFFFF" }

[notify]
# Notification
title_info = { fg = "#99FFE4", bold = true }
title_warn = { fg = "#FFC799", bold = true }
title_error = { fg = "#FF8080", bold = true }

[pick]
# Pick dialog
border = { fg = "#282828" }
active = { fg = "#FFC799", bg = "#232323" }
inactive = { fg = "#A0A0A0" }

[input]
# Input dialog
border = { fg = "#282828" }
title = { fg = "#FFC799", bold = true }
value = { fg = "#FFFFFF" }
selected = { fg = "#FFC799", bg = "#232323" }

[cmp]
# Completion
border = { fg = "#282828" }
active = { fg = "#FFC799", bg = "#232323" }
inactive = { fg = "#A0A0A0" }

# Icons
icon_file = "󰈙"
icon_folder = "󰉋"
icon_command = "󰘳"

[tasks]
# Tasks
border = { fg = "#282828" }
title = { fg = "#FFC799", bold = true }
hovered = { fg = "#FFC799", bg = "#232323" }

[help]
# Help
on = { fg = "#FFC799", bold = true }
run = { fg = "#99FFE4" }
desc = { fg = "#FFFFFF" }
hovered = { fg = "#FFC799", bg = "#232323" }
footer = { fg = "#A0A0A0" }

# Notification icons
icon_info = "󰋼"
icon_warn = "󰀦"
icon_error = "󰅚"

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#FFFFFF" },
  
  # Videos and Audio
  { mime = "video/*", fg = "#FFFFFF" },
  { mime = "audio/*", fg = "#FFFFFF" },
  
  # Archives
  { name = "*.zip", fg = "#FFFFFF" },
  { name = "*.tar", fg = "#FFFFFF" },
  { name = "*.gz", fg = "#FFFFFF" },
  { name = "*.rar", fg = "#FFFFFF" },
  
  # Documents
  { name = "*.pdf", fg = "#FFFFFF" },
  { name = "*.doc", fg = "#FFFFFF" },
  { name = "*.docx", fg = "#FFFFFF" },
  { name = "*.txt", fg = "#FFFFFF" },
  { name = "*.md", fg = "#FFFFFF" },
  
  # Code
  { name = "*.js", fg = "#FFFFFF" },
  { name = "*.ts", fg = "#FFFFFF" },
  { name = "*.py", fg = "#FFFFFF" },
  { name = "*.rs", fg = "#FFFFFF" },
  { name = "*.go", fg = "#FFFFFF" },
  { name = "*.c", fg = "#FFFFFF" },
  { name = "*.cpp", fg = "#FFFFFF" },
  { name = "*.h", fg = "#FFFFFF" },
  { name = "*.lua", fg = "#FFFFFF" },
  { name = "*.json", fg = "#FFFFFF" },
  { name = "*.toml", fg = "#FFFFFF" },
  { name = "*.yaml", fg = "#FFFFFF" },
  { name = "*.yml", fg = "#FFFFFF" },
  
  # Empty files
  { mime = "inode/empty", fg = "#505050" },
  
  # Orphan symbolic links
  { name = "*", is = "orphan", fg = "#FF8080" },
  
  # Executables
  { name = "*", is = "exec", fg = "#99FFE4" },
  
  # Fallbacks
  { name = "*", fg = "#FFFFFF" },
  { name = "*/", fg = "#A0A0A0" }
]

[icon]
prepend_conds = [
  { if = "dir", fg = "#A0A0A0", text = "󰉋" },
  { if = "link", fg = "#A0A0A0", text = "󰌹" },
  { if = "orphan", fg = "#FF8080", text = "󰌸" },
  { if = "exec", fg = "#99FFE4", text = "󰆍" }
]
